name: Build Site with EPG Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      xml_source:
        description: 'URL ou chemin du fichier XML source'
        required: false
        default: 'https://xmltvfr.fr/xmltv/xmltv_tnt.xml.gz'

jobs:
  generate-json:
    name: Generate EPG JSON
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: epg-transform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            .github
            epg-transform

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create output directory
        run: mkdir -p output

      - name: Transform XML to JSON
        run: |
          python app.py "${{ github.event.inputs.xml_source || 'https://xmltvfr.fr/xmltv/xmltv_tnt.xml.gz' }}" output/epg-data.json

      - name: Upload JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: epg-data
          path: epg-transform/output/epg-data.json
          retention-days: 1

  build-site:
    name: Build TypeScript Site
    needs: generate-json
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: epg-viewer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            .github
            epg-viewer

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Download EPG data
        uses: actions/download-artifact@v5
        with:
          name: epg-data
          path: epg-viewer/src/data

      - name: Install dependencies
        run: yarn install

      - name: Build site
        run: yarn run build
        env:
          NODE_ENV: production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build-${{ github.sha }}
          path: epg-viewer/dist/
          retention-days: 1

  deploy:
    name: Deploy to GitHub Pages
    needs: build-site
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Download build
        uses: actions/download-artifact@v5
        with:
          name: site-build-${{ github.sha }}
          path: epg-viewer/dist

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: epg-viewer/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4